services:
  backend_lts:
    build:
      context: ./backend/review-api
    network_mode: host
    image: whiskey-backend:v2.0
    restart: always
    container_name: whiskey-backend-lts

    
  frontend_lts:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
    image: whiskey-frontend:v2.0
    restart: always
    container_name: whiskey-frontend-lts
  
  # backend:
  #   build:
  #     context: ./backend
  #   network_mode: host
  #   image: whiskey-backend:v1.1
    
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   network_mode: host
  #   image: whiskey-frontend:v1.1

volumes:
  mysql_data: