services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    ports:
      - "3307:3306"
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/mysql:/var/log/mysql
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    restart: always
    networks:
      - proxy-network

  backend_lts:
    build:
      context: ./backend/review-api
    image: whiskey-backend:v3.0
    restart: always
    container_name: whiskey-backend-lts
    expose:
      - "8080"
    depends_on:
      - mariadb
    networks:
      - proxy-network
  
  backend_test:
    build:
      context: ./backend/review-api
    image: whiskey-backend:v3.0
    container_name: whiskey-backend-test
    ports:
      - "8081:8080"
    depends_on:
      - mariadb
    networks:
      - proxy-network

  frontend_lts:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
    image: whiskey-frontend:v3.0
    restart: always
    container_name: whiskey-frontend-lts
    expose:
      - "3000"
    networks:
      - proxy-network

  frontend_test:
    profiles: ["test"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
    image: whiskey-frontend:v3.0
    container_name: whiskey-frontend-test
    expose:
      - "3000"
    networks:
      - proxy-network

  selenium-chrome:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium-chrome
    shm_size: 2g
    expose:
      - "4444"
    environment:
      - TZ=Asia/Seoul
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=300
    restart: unless-stopped
    networks:
      - proxy-network

  python-app:
    build:
      context: ./backend/dc_crawling
      dockerfile: Dockerfile
    image: python-app:v1.0
    container_name: python-app
    volumes:
      - ./backend/dc_crawling:/app
    working_dir: /app
    environment:
      - TZ=Asia/Seoul
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=${MARIADB_DATABASE}
      - DB_USER=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - DISPLAY=:99
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_PW=${GMAIL_PW}
    depends_on:
      - mariadb
      - selenium-chrome
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
