services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    image: whiskey-backend:v1.1
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host
    image: whiskey-frontend:v1.1

volumes:
  mysql_data: