services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: host
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: host

volumes:
  mysql_data: