name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ubuntu
          key: ${{ secrets.IDENTITYFILE }}
          port: 2077
          command_timeout: 30m
          script: |
            set -euo pipefail
            cd /home/ubuntu/whiskey
            git pull origin main
            cd /home/ubuntu/whiskey/backend/review-api
            ./gradlew build -x test
            cd /home/ubuntu/whiskey
            docker compose up --build -d --no-deps backend_lts
