# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.IDENTITYFILE }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script_stop: true
          script: |
            echo "#start"
            echo "user=$(whoami) home=$HOME"
            cd /home/ubuntu/whiskey
            echo "############# GIT PULL #############"
            git pull origin main

            echo "############# BUILD BACKEND JAR #############"
            cd /home/ubuntu/whiskey/backend/review-api
            ./gradlew build -x test

            echo "############# DOCKER REBUILD #############"
            cd /home/ubuntu/whiskey
            docker compose up --build -d --no-deps backend_lts
